### ISSUE TITLE
screen hang on when the vnc using long time or internet bad connection

### ISSUE THREAD

**Issue by leejohannes** [norihiro/obs-vnc#28]
can we add a reload button or refresh button 
"Connection timing" seems cannot immediately reconnect VNC server

**Comment by norihiro** [comment]
As a workaround, you can force to reconnect by modifying host name or port number to a different value and set back to the original value. Does this fasten the reconnection at your setup?

Still there is a case the reconnection will take time. If current connection attempt is ongoing inside libvncclient, this plugin will wait until the ongoing attempt is done. This is because libvncclient does not support explicit abort of the reconnection.

So, if the above workaround works, it would be worth to provide the reconnect button. If not, I don't have an idea for better implementation of the reconnect button right now.

**Comment by leejohannes** [comment]
alright, let me check once it happend again
